### ISSUE TITLE
Ignition Garden renamed to Gazebo Garden

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-cmake0-feedstock#26]
### Comment:

From the next release of Ignition, all the Ignition references will be changed to "Gazebo", see https://community.gazebosim.org/t/a-new-era-for-gazebo/1356 . From the conda packaging point of view, I think this will mean that we should change name of the packages. As we already change name at each major release, I do not think it should be a big problem, we should just remember to prevent automerge from happening as it would release packages with the old name.

**Comment by traversaro** [comment]
Given that there will be this change of name, I think we can take the occasion for a few changes:
* Create new feedstock with new names, by submitting the recipes to staged-recipes, so that we will have feedstocs such as `gz-cmake-feedstock`, `gz-tools-feedstock`, etc etc. This will solve all the confusions that users have with feedstock names such as `libignition-cmake0-feedstock` or `libignition-math4-feedstock`, that would increase now that we have the `ignition/gazebo` change.
* A lot of ignition/gazebo packages now have Python bindings, so just a `lib` prefix does not make a lot of sense. What I propose is the following naming for the packate outputs:
  *  `libgz-<name><majornumber> : the C++ library
  * `gz-<name><majornumber>-python` : the Python bindings (if present)
  * `gz-<name><majornumber>` : the meta-package that installs both the C++ library and the Python bindings

fyi @conda-forge/libignition-cmake0 @conda-forge/libignition-math4 @conda-forge/libignition-tools @conda-forge/libignition-gazebo @conda-forge/libignition-utils 

If you agree, please refrain to merge any PR related to the Gazebo Garden packages, as I will submit PRs for them to staged-recipes, thanks!

**Comment by traversaro** [comment]
Related PRs:
* [ ] `gz-cmake` https://github.com/conda-forge/staged-recipes/pull/20547
* [ ] `gz-utils`
* [ ] `gz-tools` 
* [ ] `gz-math`

**Comment by traversaro** [comment]
fyi @mjcarroll, I guess you may be interested as well.

**Comment by traversaro** [comment]
The last missing PRs are https://github.com/conda-forge/staged-recipes/pull/20686 and https://github.com/conda-forge/staged-recipes/pull/20749 .

**Comment by traversaro** [comment]
> The last missing PRs are [conda-forge/staged-recipes#20686](https://github.com/conda-forge/staged-recipes/pull/20686) and [conda-forge/staged-recipes#20749](https://github.com/conda-forge/staged-recipes/pull/20749) .

The PRs have been merged, so I think we can close this issue.

**Comment by j-rivero** [comment]
Thanks so much Silvio for all the work! really welcome. Let's see if we can move the internal CI to conda in the near future.
